# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ReturnedStudent' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReturnedStudent

  target 'ReturnedStudentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReturnedStudentUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
pod 'SnapKit', '~> 3.0.2'
pod 'SDWebImage', '~> 4.0.0-beta2'
pod 'SwiftyJSON', '~> 3.1.3'
pod 'MJRefresh', '~> 3.1.12'
