# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'ReturnedStudent' do

pod 'SnapKit', '~> 3.0.2'
pod 'MJRefresh', '~> 3.1.12'
pod 'SDWebImage', '~> 4.0.0-beta2'
end
   
